---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      spring:
        applies-to: version-updates
        patterns:
          - "org.springframework*"
      kotlin:
        applies-to: version-updates
        patterns:
          - "org.jetbrains.kotlin"
          - "org.jetbrains.kotlin*"