[versions]
kotlin = "2.1.0"
spring = "3.4.2"
spring-security-test = "6.4.2"
spring-web = "6.2.2"
spring-dep-management = "1.1.7"

h2 = "2.3.232"
postgres = "42.7.5"
hibernate = "6.6.5.Final"

fasterxml-jackson = "2.18.2"
junit-launcher = "1.11.4"
jakarta = "3.1.0"
yaml = "2.3"
hikaricp = "6.2.1"
jsonwebtoken = "0.12.6"

[libraries]
springboot-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat", version.ref = "spring" }
springboot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring" }
springboot-logging = { module = "org.springframework.boot:spring-boot-starter-logging", version.ref = "spring" }
springboot-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring" }
springboot-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "spring-security-test" }
springboot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring" }
spring-datajpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "spring" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-web" } # ?
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring-web" }
spring-websocket = { module = "org.springframework:spring-websocket", version.ref = "spring-web" }
spring-messaging = { module = "org.springframework:spring-messaging", version.ref = "spring-web" }

fasterxml-jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "fasterxml-jackson" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
h2-database = { module = "com.h2database:h2", version.ref = "h2" }
junit-plateform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }
yaml-snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "yaml" }
zaxxer-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
jsonwebtoken-jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jsonwebtoken"}
jsonwebtoken-jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jsonwebtoken"}
jsonwebtoken-jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jsonwebtoken"}

[plugins]
springboot-framework = { id = "org.springframework.boot", version.ref = "spring" }
springboot-dep-management = { id = "io.spring.dependency-management", version.ref = "spring-dep-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
