spring:
  application:
    name: "ChatterBox"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
server:
  port: 8080

app:
  jwt:
    secret: "my-secret"
    acces-token-expiration: 1200000
    refresh-token-expiration: 86400000